import Logger from '../../../Logging Middleware/src/index.js';

const logger = new Logger({
    accessToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJyaXNoYWIyMjEzMjEwQGFrZ2VjLmFjLmluIiwiZXhwIjoxNzUyNTU3MDMyLCJpYXQiOjE3NTI1NTYxMzIsImlzcyI6IkFmZm9yZCBNZWRpY2FsIFRlY2hub2xvZ2llcyBQcml2YXRlIExpbWl0ZWQiLCJqdGkiOiI5Nzg0Zjc5OC03Y2RjLTRmY2YtODZjNS00ZTMzMzk5YWNmMmEiLCJsb2NhbGUiOiJlbi1JTiIsIm5hbWUiOiJyaXNoYWIgY2hhdWRoYXJ5Iiwic3ViIjoiYWNmOTJlMmQtZmFjMi00NDc4LTkyMGMtNDg0YWUwZjg3NTI3In0sImVtYWlsIjoicmlzaGFiMjIxMzIxMEBha2dlYy5hYy5pbiIsIm5hbWUiOiJyaXNoYWIgY2hhdWRoYXJ5Iiwicm9sbE5vIjoiMjIwMDI3MDEzMDEzNiIsImFjY2Vzc0NvZGUiOiJ1dU1ieVkiLCJjbGllbnRJRCI6ImFjZjkyZTJkLWZhYzItNDQ3OC05MjBjLTQ4NGFlMGY4NzUyNyIsImNsaWVudFNlY3JldCI6IlZXS1pFRGpUdERheFd3dGEifQ.R1u_5BOhagQ8e-4sgfgDcpaVYjZbH7pA8farEqxGjAM'
});

export default logger;
